<a href="https://colab.research.google.com/github/drskprabhakar/AI-ML-DL-colab-notebooks-coding-models/blob/main/13825Kalyani_3_follows.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd
import numpy as np
df = pd.read_excel('/content/drive/MyDrive/Kalyani 3 followups AR.xlsx')
sheets = pd.ExcelFile('/content/drive/MyDrive/Kalyani 3 followups AR.xlsx')
sheets.sheet_names

['day1AR', '6weeksAR', '3monthsAR']

In [16]:
day1AR = sheets.parse('day1AR')
wk6AR = sheets.parse('6weeksAR')
mth3AR = sheets.parse('3monthsAR')

In [17]:
day1AR.shape, day1AR.columns

((131, 16),
 Index(['AGE', 'SEX_numeric', 'KH', 'KV', 'AX', 'V/A PRE OP', 'numerator',
        'denominator', 'preop logMAR', 'POD 1 DAY V/A', 'numerator.1',
        'denominator.1', 'day1 logMAR', 'SPH', 'CYL', 'AXIS'],
       dtype='object'))

In [20]:
day1ARAK = day1AR[['AGE', 'SEX_numeric', 'KH', 'KV', 'AX','preop logMAR','day1 logMAR', 'SPH', 'CYL', 'AXIS']]
day1ARAK

,AGE,SEX_numeric,KH,KV,AX,preop logMAR,day1 logMAR,SPH,CYL,AXIS
0,54,1,46.50,47.25,155,0.602060,0.301030,0.25,-1.50,115
1,63,1,46.75,48.00,80,2.301030,0.477121,0.75,-2.25,80
2,71,1,45.25,45.75,120,1.778151,0.477121,-0.75,-1.00,160
3,89,0,45.50,47.00,80,0.778151,0.301030,0.25,2.00,75
4,59,1,42.50,43.50,75,1.000000,0.602060,2.00,-2.00,90
...,...,...,...,...,...,...,...,...,...,...
126,66,1,43.25,44.00,60,1.000000,0.602060,-2.75,-3.00,60
127,57,1,47.00,48.25,165,0.602060,0.176091,1.25,-1.75,15
128,52,1,42.00,42.50,110,1.778151,0.301030,-0.75,-1.25,95
129,54,0,45.00,46.25,165,0.778151,0.477121,-2.75,-3.00,75
130,52,0,44.75,44.75,180,0.778151,0.602060,-3.25,-3.00,40

In [22]:
day1ARAK.columns

Index(['AGE', 'SEX_numeric', 'KH', 'KV', 'AX', 'preop logMAR', 'day1 logMAR',
       'SPH', 'CYL', 'AXIS'],
      dtype='object')

In [23]:
day1ARAK.isnull().sum()

AGE             0
SEX_numeric     0
KH              0
KV              0
AX              0
preop logMAR    0
day1 logMAR     0
SPH             0
CYL             0
AXIS            0
dtype: int64

In [24]:
day1ARAK.describe()

,AGE,SEX_numeric,KH,KV,AX,preop logMAR,day1 logMAR,SPH,CYL,AXIS
count,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000
mean,63.839695,0.625954,44.553435,45.345420,104.198473,1.337971,0.372322,0.190840,-1.500000,89.259542
std,9.656259,0.485733,1.615433,1.669713,50.393898,0.648344,0.200949,1.412456,1.911755,37.404975
min,38.000000,0.000000,40.000000,41.250000,5.000000,0.000000,0.000000,-3.250000,-5.750000,5.000000
25%,56.000000,0.000000,43.500000,44.125000,75.000000,0.778151,0.176091,-0.750000,-2.750000,72.500000
50%,65.000000,1.000000,44.750000,45.250000,90.000000,1.301030,0.301030,0.250000,-1.500000,90.000000
75%,71.000000,1.000000,45.500000,46.500000,155.000000,1.778151,0.477121,1.250000,-0.750000,102.500000
max,93.000000,1.000000,48.500000,49.500000,180.000000,2.778151,1.301030,3.500000,3.750000,180.000000

In [25]:
day1ARAK.corr()

,AGE,SEX_numeric,KH,KV,AX,preop logMAR,day1 logMAR,SPH,CYL,AXIS
AGE,1.000000,0.010078,-0.041116,-0.002384,-0.210272,-0.079381,0.203048,0.132260,-0.082297,0.075103
SEX_numeric,0.010078,1.000000,0.187422,0.162903,-0.067337,0.016944,-0.093151,0.074012,-0.035206,0.113769
KH,-0.041116,0.187422,1.000000,0.942591,0.064784,-0.099052,-0.059560,0.034477,-0.069586,0.103171
KV,-0.002384,0.162903,0.942591,1.000000,0.042055,-0.051368,-0.068860,0.017701,-0.057384,0.081597
AX,-0.210272,-0.067337,0.064784,0.042055,1.000000,-0.171008,-0.110551,-0.018233,-0.057189,0.020087
preop logMAR,-0.079381,0.016944,-0.099052,-0.051368,-0.171008,1.000000,0.298275,-0.067073,0.062275,0.072838
day1 logMAR,0.203048,-0.093151,-0.059560,-0.068860,-0.110551,0.298275,1.000000,-0.069284,-0.123313,-0.060967
SPH,0.132260,0.074012,0.034477,0.017701,-0.018233,-0.067073,-0.069284,1.000000,0.055372,-0.006477
CYL,-0.082297,-0.035206,-0.069586,-0.057384,-0.057189,0.062275,-0.123313,0.055372,1.000000,0.084981
AXIS,0.075103,0.113769,0.103171,0.081597,0.020087,0.072838,-0.060967,-0.006477,0.084981,1.000000

In [26]:
day1ARAK.columns

Index(['AGE', 'SEX_numeric', 'KH', 'KV', 'AX', 'preop logMAR', 'day1 logMAR',
       'SPH', 'CYL', 'AXIS'],
      dtype='object')

In [33]:
arak = day1ARAK[['KH', 'KV', 'AX','SPH', 'CYL', 'AXIS']]
arak

        KH     KV   AX   SPH   CYL  AXIS
0    46.50  47.25  155  0.25 -1.50   115
1    46.75  48.00   80  0.75 -2.25    80
2    45.25  45.75  120 -0.75 -1.00   160
3    45.50  47.00   80  0.25  2.00    75
4    42.50  43.50   75  2.00 -2.00    90
..     ...    ...  ...   ...   ...   ...
126  43.25  44.00   60 -2.75 -3.00    60
127  47.00  48.25  165  1.25 -1.75    15
128  42.00  42.50  110 -0.75 -1.25    95
129  45.00  46.25  165 -2.75 -3.00    75
130  44.75  44.75  180 -3.25 -3.00    40

[131 rows x 6 columns]

In [34]:
arak.describe()

               KH          KV          AX         SPH         CYL        AXIS
count  131.000000  131.000000  131.000000  131.000000  131.000000  131.000000
mean    44.553435   45.345420  104.198473    0.190840   -1.500000   89.259542
std      1.615433    1.669713   50.393898    1.412456    1.911755   37.404975
min     40.000000   41.250000    5.000000   -3.250000   -5.750000    5.000000
25%     43.500000   44.125000   75.000000   -0.750000   -2.750000   72.500000
50%     44.750000   45.250000   90.000000    0.250000   -1.500000   90.000000
75%     45.500000   46.500000  155.000000    1.250000   -0.750000  102.500000
max     48.500000   49.500000  180.000000    3.500000    3.750000  180.000000

In [35]:
arak.corr()

            KH        KV        AX       SPH       CYL      AXIS
KH    1.000000  0.942591  0.064784  0.034477 -0.069586  0.103171
KV    0.942591  1.000000  0.042055  0.017701 -0.057384  0.081597
AX    0.064784  0.042055  1.000000 -0.018233 -0.057189  0.020087
SPH   0.034477  0.017701 -0.018233  1.000000  0.055372 -0.006477
CYL  -0.069586 -0.057384 -0.057189  0.055372  1.000000  0.084981
AXIS  0.103171  0.081597  0.020087 -0.006477  0.084981  1.000000

In [38]:
da1logmar = day1ARAK[['preop logMAR', 'day1 logMAR']]
da1logmar

     preop logMAR  day1 logMAR
0        0.602060     0.301030
1        2.301030     0.477121
2        1.778151     0.477121
3        0.778151     0.301030
4        1.000000     0.602060
..            ...          ...
126      1.000000     0.602060
127      0.602060     0.176091
128      1.778151     0.301030
129      0.778151     0.477121
130      0.778151     0.602060

[131 rows x 2 columns]

In [39]:
da1logmar.describe()

       preop logMAR  day1 logMAR
count    131.000000   131.000000
mean       1.337971     0.372322
std        0.648344     0.200949
min        0.000000     0.000000
25%        0.778151     0.176091
50%        1.301030     0.301030
75%        1.778151     0.477121
max        2.778151     1.301030

In [40]:
da1logmar.corr()

              preop logMAR  day1 logMAR
preop logMAR      1.000000     0.298275
day1 logMAR       0.298275     1.000000

In [52]:
day1ARAK.columns

Index(['AGE', 'SEX_numeric', 'KH', 'KV', 'AX', 'preop logMAR', 'day1 logMAR',
       'SPH', 'CYL', 'AXIS', 'preopcyl', 'postopcyl'],
      dtype='object')

In [51]:
day1ARAK['preopcyl'] = day1ARAK['KV']-day1ARAK['KH']
day1ARAK['postopcyl'] = day1ARAK['CYL']

/tmp/ipython-input-2318472309.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day1ARAK['preopcyl'] = day1ARAK['KV']-day1ARAK['KH']
/tmp/ipython-input-2318472309.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day1ARAK['postopcyl'] = day1ARAK['CYL']

In [54]:
day1prepostcyl = day1ARAK[['preopcyl', 'postopcyl']]

In [55]:
day1prepostcyl.describe()

         preopcyl   postopcyl
count  131.000000  131.000000
mean     0.791985   -1.500000
std      0.559148    1.911755
min      0.000000   -5.750000
25%      0.500000   -2.750000
50%      0.750000   -1.500000
75%      1.000000   -0.750000
max      3.000000    3.750000

In [56]:
day1prepostcyl.corr()

           preopcyl  postopcyl
preopcyl   1.000000   0.029684
postopcyl  0.029684   1.000000

In [57]:
# Create a new column 'Classification' in day1ARclean
day1AR['Classification'] = day1AR.apply(
    lambda row: 'compound Myopic Astigmatism' if row['SPH'] < 0 and row['CYL'] < 0 else
                'compound Hyperopic Astigmatism' if row['SPH'] > 0 and row['CYL'] > 0 else
    'simple myopic astigmatism' if row['SPH'] == 0 and row['CYL'] < 0 else
    'simple hyperopic astigmatism' if row['SPH'] == 0 and row['CYL'] > 0 else
                'mixed astigmatism',
    axis=1
)

# View result
print(day1AR[['SPH', 'CYL', 'AXIS','Classification']])

      SPH   CYL  AXIS                  Classification
0    0.25 -1.50   115               mixed astigmatism
1    0.75 -2.25    80               mixed astigmatism
2   -0.75 -1.00   160     compound Myopic Astigmatism
3    0.25  2.00    75  compound Hyperopic Astigmatism
4    2.00 -2.00    90               mixed astigmatism
..    ...   ...   ...                             ...
126 -2.75 -3.00    60     compound Myopic Astigmatism
127  1.25 -1.75    15               mixed astigmatism
128 -0.75 -1.25    95     compound Myopic Astigmatism
129 -2.75 -3.00    75     compound Myopic Astigmatism
130 -3.25 -3.00    40     compound Myopic Astigmatism

[131 rows x 4 columns]