<a href="https://colab.research.google.com/github/drskprabhakar/AI-ML-DL-colab-notebooks-coding-models/blob/main/Aishwarya_sia_algorithm_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [6]:
df=pd.read_excel('/content/drive/MyDrive/aishwarya preopkhkvax.xlsx')

In [7]:
df

     pre-op KH  pre-op KV  pre-op Axis  post-op KH  post-op KV  post-op Axis
0        43.50      44.00           90       43.25       44.75            10
1        44.25      44.50           45       41.25       44.50            70
2        47.75      49.50            5       46.00       47.75            35
3        43.75      44.75          165       42.75       45.00           150
4        44.25      44.75           85       44.50       45.50            40
..         ...        ...          ...         ...         ...           ...
102      43.00      43.50          100       43.00       43.75           170
103      45.75      46.25           30       45.75       47.00             5
104      45.25      46.00          135       44.25       45.50           155
105      46.00      46.50           40       46.25       48.00             5
106      42.25      42.75          110       42.00       42.25            65

[107 rows x 6 columns]

In [8]:
df.columns

Index(['pre-op KH', 'pre-op KV', 'pre-op Axis', 'post-op KH', 'post-op KV',
       'post-op Axis'],
      dtype='object')

In [61]:

# double-angle vector analysis (Pythagorean vector method)

# preop magnitude = M1 = pre-op KV-pre-op KH
# preop axis = A1
# postop magnitude = M2 = post-op KV-post-op KH
# postop axis = A2

# 1. Convert pre-op astigmatism to vector components
    # X1 = M1​*cos(2A1)
    # Y1 = M1*sin(2A1)

# 2. Convert post-op astigmatism to vector components
    # X2 = M2*cos(2A2)
    # Y2 = M2*sin(2A2)

# 3. Calculate SIA vector components:
    # Xsia = X2-X1
    # Ysia = Y2-Y1

# 4. Calculate SIA magnitude
    # SIA Magnitude = ​	sqrt*Xsia*2+Ysia*2

# 5. Calculate SIA axis (single-angle, in degrees)
    # SIA Axis = 1/2*tan inverse(Ysia/Xsia)

In [62]:
# prompt: pre_op KV -pre_op KH
# finding M1

df['M1'] = df['pre-op KV'] - df['pre-op KH']
df['M1']

0      0.50
1      0.25
2      1.75
3      1.00
4      0.50
       ...
102    0.50
103    0.50
104    0.75
105    0.50
106    0.50
Name: M1, Length: 107, dtype: float64

In [38]:
# finding M2 by subtracting
# post-op KV-post-op KH

df['M2'] = df['post-op KV'] - df['post-op KH']
df['M2']

0      1.50
1      3.25
2      1.75
3      2.25
4      1.00
       ...
102    0.75
103    1.25
104    1.25
105    1.75
106    0.25
Name: M2, Length: 107, dtype: float64

In [40]:
# now df contains columns M1 and M2
# finding pre-op astigmatism vectors

# X1 = M1 * cos2*pre-op Axis
# Y1 = M1 * sin2*pre-op Axix

In [41]:
# prompt: M1*cos2*pre-op Axis

import numpy as np
df['X1'] = df['M1'] * np.cos(2 * np.deg2rad(df['pre-op Axis']))
df['Y1'] = df['M1'] * np.sin(2 * np.deg2rad(df['pre-op Axis']))

In [42]:
df['X1'], df['Y1']

(0     -5.000000e-01
 1      1.530808e-17
 2      1.723414e+00
 3      8.660254e-01
 4     -4.924039e-01
            ...
 102   -4.698463e-01
 103    2.500000e-01
 104   -1.377728e-16
 105    8.682409e-02
 106   -3.830222e-01
 Name: X1, Length: 107, dtype: float64,
 0      6.123234e-17
 1      2.500000e-01
 2      3.038843e-01
 3     -5.000000e-01
 4      8.682409e-02
            ...
 102   -1.710101e-01
 103    4.330127e-01
 104   -7.500000e-01
 105    4.924039e-01
 106   -3.213938e-01
 Name: Y1, Length: 107, dtype: float64)

In [43]:
df

,pre-op KH,pre-op KV,pre-op Axis,post-op KH,post-op KV,post-op Axis,M1,M2,X1,Y1
0,43.50,44.00,90,43.25,44.75,10,0.50,1.50,-5.000000e-01,6.123234e-17
1,44.25,44.50,45,41.25,44.50,70,0.25,3.25,1.530808e-17,2.500000e-01
2,47.75,49.50,5,46.00,47.75,35,1.75,1.75,1.723414e+00,3.038843e-01
3,43.75,44.75,165,42.75,45.00,150,1.00,2.25,8.660254e-01,-5.000000e-01
4,44.25,44.75,85,44.50,45.50,40,0.50,1.00,-4.924039e-01,8.682409e-02
...,...,...,...,...,...,...,...,...,...,...
102,43.00,43.50,100,43.00,43.75,170,0.50,0.75,-4.698463e-01,-1.710101e-01
103,45.75,46.25,30,45.75,47.00,5,0.50,1.25,2.500000e-01,4.330127e-01
104,45.25,46.00,135,44.25,45.50,155,0.75,1.25,-1.377728e-16,-7.500000e-01
105,46.00,46.50,40,46.25,48.00,5,0.50,1.75,8.682409e-02,4.924039e-01
106,42.25,42.75,110,42.00,42.25,65,0.50,0.25,-3.830222e-01,-3.213938e-01

In [47]:
# prompt: M2*cos2*pre-op Axis
# finding post-op astigmatism vecors

import numpy as np
df['X2'] = df['M2'] * np.cos(2 * np.deg2rad(df['post-op Axis']))
df['Y2'] = df['M2'] * np.sin(2 * np.deg2rad(df['post-op Axis']))

In [48]:
df['X2'], df['Y2']

(0      1.409539
 1     -2.489644
 2      0.598535
 3      1.125000
 4      0.173648
          ...
 102    0.704769
 103    1.231010
 104    0.803485
 105    1.723414
 106   -0.160697
 Name: X2, Length: 107, dtype: float64,
 0      0.513030
 1      2.089060
 2      1.644462
 3     -1.948557
 4      0.984808
          ...
 102   -0.256515
 103    0.217060
 104   -0.957556
 105    0.303884
 106    0.191511
 Name: Y2, Length: 107, dtype: float64)

In [49]:
df

,pre-op KH,pre-op KV,pre-op Axis,post-op KH,post-op KV,post-op Axis,M1,M2,X1,Y1,X2,Y2
0,43.50,44.00,90,43.25,44.75,10,0.50,1.50,-5.000000e-01,6.123234e-17,1.409539,0.513030
1,44.25,44.50,45,41.25,44.50,70,0.25,3.25,1.530808e-17,2.500000e-01,-2.489644,2.089060
2,47.75,49.50,5,46.00,47.75,35,1.75,1.75,1.723414e+00,3.038843e-01,0.598535,1.644462
3,43.75,44.75,165,42.75,45.00,150,1.00,2.25,8.660254e-01,-5.000000e-01,1.125000,-1.948557
4,44.25,44.75,85,44.50,45.50,40,0.50,1.00,-4.924039e-01,8.682409e-02,0.173648,0.984808
...,...,...,...,...,...,...,...,...,...,...,...,...
102,43.00,43.50,100,43.00,43.75,170,0.50,0.75,-4.698463e-01,-1.710101e-01,0.704769,-0.256515
103,45.75,46.25,30,45.75,47.00,5,0.50,1.25,2.500000e-01,4.330127e-01,1.231010,0.217060
104,45.25,46.00,135,44.25,45.50,155,0.75,1.25,-1.377728e-16,-7.500000e-01,0.803485,-0.957556
105,46.00,46.50,40,46.25,48.00,5,0.50,1.75,8.682409e-02,4.924039e-01,1.723414,0.303884
106,42.25,42.75,110,42.00,42.25,65,0.50,0.25,-3.830222e-01,-3.213938e-01,-0.160697,0.191511

In [57]:
df['Xsia'] = df['X2']-df['X1']
df['Ysia'] = df['Y2']-df['Y1']

In [59]:
df['Xsia'], df['Ysia']

(0      1.909539
 1     -2.489644
 2     -1.124878
 3      0.258975
 4      0.666052
          ...
 102    1.174616
 103    0.981010
 104    0.803485
 105    1.636589
 106    0.222325
 Name: Xsia, Length: 107, dtype: float64,
 0      0.513030
 1      1.839060
 2      1.340578
 3     -1.448557
 4      0.897984
          ...
 102   -0.085505
 103   -0.215952
 104   -0.207556
 105   -0.188520
 106    0.512905
 Name: Ysia, Length: 107, dtype: float64)

In [60]:
df

,pre-op KH,pre-op KV,pre-op Axis,post-op KH,post-op KV,post-op Axis,M1,M2,X1,Y1,X2,Y2,Xsia,Ysia
0,43.50,44.00,90,43.25,44.75,10,0.50,1.50,-5.000000e-01,6.123234e-17,1.409539,0.513030,1.909539,0.513030
1,44.25,44.50,45,41.25,44.50,70,0.25,3.25,1.530808e-17,2.500000e-01,-2.489644,2.089060,-2.489644,1.839060
2,47.75,49.50,5,46.00,47.75,35,1.75,1.75,1.723414e+00,3.038843e-01,0.598535,1.644462,-1.124878,1.340578
3,43.75,44.75,165,42.75,45.00,150,1.00,2.25,8.660254e-01,-5.000000e-01,1.125000,-1.948557,0.258975,-1.448557
4,44.25,44.75,85,44.50,45.50,40,0.50,1.00,-4.924039e-01,8.682409e-02,0.173648,0.984808,0.666052,0.897984
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,43.00,43.50,100,43.00,43.75,170,0.50,0.75,-4.698463e-01,-1.710101e-01,0.704769,-0.256515,1.174616,-0.085505
103,45.75,46.25,30,45.75,47.00,5,0.50,1.25,2.500000e-01,4.330127e-01,1.231010,0.217060,0.981010,-0.215952
104,45.25,46.00,135,44.25,45.50,155,0.75,1.25,-1.377728e-16,-7.500000e-01,0.803485,-0.957556,0.803485,-0.207556
105,46.00,46.50,40,46.25,48.00,5,0.50,1.75,8.682409e-02,4.924039e-01,1.723414,0.303884,1.636589,-0.188520
106,42.25,42.75,110,42.00,42.25,65,0.50,0.25,-3.830222e-01,-3.213938e-01,-0.160697,0.191511,0.222325,0.512905

In [66]:
# finding SIA magnitude

df['SIA_magnitude'] = np.sqrt(df['Xsia']**2 + df['Ysia']**2)
df['SIA_magnitude']

0      1.977255
1      3.095233
2      1.750000
3      1.471525
4      1.118034
         ...
102    1.177724
103    1.004498
104    0.829859
105    1.647412
106    0.559017
Name: SIA_magnitude, Length: 107, dtype: float64

In [67]:
df

,pre-op KH,pre-op KV,pre-op Axis,post-op KH,post-op KV,post-op Axis,M1,M2,X1,Y1,X2,Y2,Xsia,Ysia,SIA_magnitude
0,43.50,44.00,90,43.25,44.75,10,0.50,1.50,-5.000000e-01,6.123234e-17,1.409539,0.513030,1.909539,0.513030,1.977255
1,44.25,44.50,45,41.25,44.50,70,0.25,3.25,1.530808e-17,2.500000e-01,-2.489644,2.089060,-2.489644,1.839060,3.095233
2,47.75,49.50,5,46.00,47.75,35,1.75,1.75,1.723414e+00,3.038843e-01,0.598535,1.644462,-1.124878,1.340578,1.750000
3,43.75,44.75,165,42.75,45.00,150,1.00,2.25,8.660254e-01,-5.000000e-01,1.125000,-1.948557,0.258975,-1.448557,1.471525
4,44.25,44.75,85,44.50,45.50,40,0.50,1.00,-4.924039e-01,8.682409e-02,0.173648,0.984808,0.666052,0.897984,1.118034
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,43.00,43.50,100,43.00,43.75,170,0.50,0.75,-4.698463e-01,-1.710101e-01,0.704769,-0.256515,1.174616,-0.085505,1.177724
103,45.75,46.25,30,45.75,47.00,5,0.50,1.25,2.500000e-01,4.330127e-01,1.231010,0.217060,0.981010,-0.215952,1.004498
104,45.25,46.00,135,44.25,45.50,155,0.75,1.25,-1.377728e-16,-7.500000e-01,0.803485,-0.957556,0.803485,-0.207556,0.829859
105,46.00,46.50,40,46.25,48.00,5,0.50,1.75,8.682409e-02,4.924039e-01,1.723414,0.303884,1.636589,-0.188520,1.647412
106,42.25,42.75,110,42.00,42.25,65,0.50,0.25,-3.830222e-01,-3.213938e-01,-0.160697,0.191511,0.222325,0.512905,0.559017

In [68]:
# findinf SIA axis

df['SIA_axis'] = np.arctan(df['Ysia']/df['Xsia'])
df['SIA_axis']

0      0.262469
1     -0.636219
2     -0.872665
3     -1.393884
4      0.932616
         ...
102   -0.072666
103   -0.216677
104   -0.252793
105   -0.114685
106    1.161779
Name: SIA_axis, Length: 107, dtype: float64

In [70]:
# prompt: Radians or degrees

import numpy as np
df['SIA_axis'] = np.rad2deg(np.arctan(df['Ysia']/df['Xsia']))
df['SIA_axis']

0      15.038369
1     -36.452677
2     -50.000000
3     -79.863688
4      53.434949
         ...
102    -4.163448
103   -12.414680
104   -14.483980
105    -6.570969
106    66.565051
Name: SIA_axis, Length: 107, dtype: float64

In [71]:
df

,pre-op KH,pre-op KV,pre-op Axis,post-op KH,post-op KV,post-op Axis,M1,M2,X1,Y1,X2,Y2,Xsia,Ysia,SIA_magnitude,SIA_axis
0,43.50,44.00,90,43.25,44.75,10,0.50,1.50,-5.000000e-01,6.123234e-17,1.409539,0.513030,1.909539,0.513030,1.977255,15.038369
1,44.25,44.50,45,41.25,44.50,70,0.25,3.25,1.530808e-17,2.500000e-01,-2.489644,2.089060,-2.489644,1.839060,3.095233,-36.452677
2,47.75,49.50,5,46.00,47.75,35,1.75,1.75,1.723414e+00,3.038843e-01,0.598535,1.644462,-1.124878,1.340578,1.750000,-50.000000
3,43.75,44.75,165,42.75,45.00,150,1.00,2.25,8.660254e-01,-5.000000e-01,1.125000,-1.948557,0.258975,-1.448557,1.471525,-79.863688
4,44.25,44.75,85,44.50,45.50,40,0.50,1.00,-4.924039e-01,8.682409e-02,0.173648,0.984808,0.666052,0.897984,1.118034,53.434949
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,43.00,43.50,100,43.00,43.75,170,0.50,0.75,-4.698463e-01,-1.710101e-01,0.704769,-0.256515,1.174616,-0.085505,1.177724,-4.163448
103,45.75,46.25,30,45.75,47.00,5,0.50,1.25,2.500000e-01,4.330127e-01,1.231010,0.217060,0.981010,-0.215952,1.004498,-12.414680
104,45.25,46.00,135,44.25,45.50,155,0.75,1.25,-1.377728e-16,-7.500000e-01,0.803485,-0.957556,0.803485,-0.207556,0.829859,-14.483980
105,46.00,46.50,40,46.25,48.00,5,0.50,1.75,8.682409e-02,4.924039e-01,1.723414,0.303884,1.636589,-0.188520,1.647412,-6.570969
106,42.25,42.75,110,42.00,42.25,65,0.50,0.25,-3.830222e-01,-3.213938e-01,-0.160697,0.191511,0.222325,0.512905,0.559017,66.565051

In [81]:
# prompt: SIA axis = 1/2tan inverse(Ysia/Xsia)

import numpy as np
# findinf SIA axis (corrected for the 1/2 factor and potential quadrants)

# Use arctan2 for correct quadrant handling
df['SIA_axis'] = 0.5 * np.arctan2(df['Ysia'], df['Xsia'])

# Convert to degrees
df['SIA_axis'] = np.rad2deg(df['SIA_axis'])

# Handle potential angles outside the desired range (0 to 180 degrees)
# Add 180 if the angle is negative to bring it into the 0-180 range
df['SIA_axis'] = df['SIA_axis'].apply(lambda x: x + 180 if x < 0 else x)

# If the axis is 0 (due to Xsia=0 and Ysia=0), leave it as 0. Otherwise, ensure it's not 180.
# This handles cases where SIA_axis might become 180 when Ysia is 0.
df['SIA_axis'] = df.apply(lambda row: 0 if (row['Xsia'] == 0 and row['Ysia'] == 0) else (row['SIA_axis'] % 180), axis=1)

df['SIA_axis']
df

,pre-op KH,pre-op KV,pre-op Axis,post-op KH,post-op KV,post-op Axis,M1,M2,X1,Y1,X2,Y2,Xsia,Ysia,SIA_magnitude,SIA_axis,SIA-axis
0,43.50,44.00,90,43.25,44.75,10,0.50,1.50,-5.000000e-01,6.123234e-17,1.409539,0.513030,1.909539,0.513030,1.977255,7.519184,7.890392
1,44.25,44.50,45,41.25,44.50,70,0.25,3.25,1.530808e-17,2.500000e-01,-2.489644,2.089060,-2.489644,1.839060,3.095233,71.773661,-27.146053
2,47.75,49.50,5,46.00,47.75,35,1.75,1.75,1.723414e+00,3.038843e-01,0.598535,1.644462,-1.124878,1.340578,1.750000,65.000000,NaN
3,43.75,44.75,165,42.75,45.00,150,1.00,2.25,8.660254e-01,-5.000000e-01,1.125000,-1.948557,0.258975,-1.448557,1.471525,140.068156,NaN
4,44.25,44.75,85,44.50,45.50,40,0.50,1.00,-4.924039e-01,8.682409e-02,0.173648,0.984808,0.666052,0.897984,1.118034,26.717474,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,43.00,43.50,100,43.00,43.75,170,0.50,0.75,-4.698463e-01,-1.710101e-01,0.704769,-0.256515,1.174616,-0.085505,1.177724,177.918276,-2.089091
103,45.75,46.25,30,45.75,47.00,5,0.50,1.25,2.500000e-01,4.330127e-01,1.231010,0.217060,0.981010,-0.215952,1.004498,173.792660,-6.411276
104,45.25,46.00,135,44.25,45.50,155,0.75,1.25,-1.377728e-16,-7.500000e-01,0.803485,-0.957556,0.803485,-0.207556,0.829859,172.758010,-7.571829
105,46.00,46.50,40,46.25,48.00,5,0.50,1.75,8.682409e-02,4.924039e-01,1.723414,0.303884,1.636589,-0.188520,1.647412,176.714516,-3.314678
106,42.25,42.75,110,42.00,42.25,65,0.50,0.25,-3.830222e-01,-3.213938e-01,-0.160697,0.191511,0.222325,0.512905,0.559017,33.282526,NaN

In [78]:
df['SIA-axis'] = 0.5 * np.arctanh(df['Ysia']/df['Xsia'])
df['SIA-axis'] = np.rad2deg(df['SIA-axis'])

/usr/local/lib/python3.11/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: invalid value encountered in arctanh
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [79]:
df['SIA-axis']

0       7.890392
1     -27.146053
2            NaN
3            NaN
4            NaN
         ...
102    -2.089091
103    -6.411276
104    -7.571829
105    -3.314678
106          NaN
Name: SIA-axis, Length: 107, dtype: float64

In [80]:
df

,pre-op KH,pre-op KV,pre-op Axis,post-op KH,post-op KV,post-op Axis,M1,M2,X1,Y1,X2,Y2,Xsia,Ysia,SIA_magnitude,SIA_axis,SIA-axis
0,43.50,44.00,90,43.25,44.75,10,0.50,1.50,-5.000000e-01,6.123234e-17,1.409539,0.513030,1.909539,0.513030,1.977255,15.038369,7.890392
1,44.25,44.50,45,41.25,44.50,70,0.25,3.25,1.530808e-17,2.500000e-01,-2.489644,2.089060,-2.489644,1.839060,3.095233,-36.452677,-27.146053
2,47.75,49.50,5,46.00,47.75,35,1.75,1.75,1.723414e+00,3.038843e-01,0.598535,1.644462,-1.124878,1.340578,1.750000,-50.000000,NaN
3,43.75,44.75,165,42.75,45.00,150,1.00,2.25,8.660254e-01,-5.000000e-01,1.125000,-1.948557,0.258975,-1.448557,1.471525,-79.863688,NaN
4,44.25,44.75,85,44.50,45.50,40,0.50,1.00,-4.924039e-01,8.682409e-02,0.173648,0.984808,0.666052,0.897984,1.118034,53.434949,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,43.00,43.50,100,43.00,43.75,170,0.50,0.75,-4.698463e-01,-1.710101e-01,0.704769,-0.256515,1.174616,-0.085505,1.177724,-4.163448,-2.089091
103,45.75,46.25,30,45.75,47.00,5,0.50,1.25,2.500000e-01,4.330127e-01,1.231010,0.217060,0.981010,-0.215952,1.004498,-12.414680,-6.411276
104,45.25,46.00,135,44.25,45.50,155,0.75,1.25,-1.377728e-16,-7.500000e-01,0.803485,-0.957556,0.803485,-0.207556,0.829859,-14.483980,-7.571829
105,46.00,46.50,40,46.25,48.00,5,0.50,1.75,8.682409e-02,4.924039e-01,1.723414,0.303884,1.636589,-0.188520,1.647412,-6.570969,-3.314678
106,42.25,42.75,110,42.00,42.25,65,0.50,0.25,-3.830222e-01,-3.213938e-01,-0.160697,0.191511,0.222325,0.512905,0.559017,66.565051,NaN

In [96]:
import numpy as np

# Use np.arctan2 for correct quadrant handling and vectorized calculation
df['sia_axis'] = 0.5 * np.arctan2(df['Ysia'], df['Xsia'])

# Convert to degrees using np.rad2deg
df['sia_axis'] = np.rad2deg(df['sia_axis'])

# Ensure the axis is in the 0-180 range by taking the modulo 180
# This handles both negative angles and angles > 180
# For the specific case where Xsia=0 and Ysia=0 (resulting in 0 SIA magnitude and potentially an arbitrary axis),
# the arctan2 will return 0, and 0 % 180 is 0, which is the desired behavior.
df['sia_axis'] = df['sia_axis'] % 180

df['sia_axis']
df

,pre-op KH,pre-op KV,pre-op Axis,post-op KH,post-op KV,post-op Axis,M1,M2,X1,Y1,X2,Y2,Xsia,Ysia,SIA_magnitude,SIA_axis,SIA-axis,sia_axis
0,43.50,44.00,90,43.25,44.75,10,0.50,1.50,-5.000000e-01,6.123234e-17,1.409539,0.513030,1.909539,0.513030,1.977255,7.519184,7.890392,7.519184
1,44.25,44.50,45,41.25,44.50,70,0.25,3.25,1.530808e-17,2.500000e-01,-2.489644,2.089060,-2.489644,1.839060,3.095233,71.773661,-27.146053,71.773661
2,47.75,49.50,5,46.00,47.75,35,1.75,1.75,1.723414e+00,3.038843e-01,0.598535,1.644462,-1.124878,1.340578,1.750000,65.000000,NaN,65.000000
3,43.75,44.75,165,42.75,45.00,150,1.00,2.25,8.660254e-01,-5.000000e-01,1.125000,-1.948557,0.258975,-1.448557,1.471525,140.068156,NaN,140.068156
4,44.25,44.75,85,44.50,45.50,40,0.50,1.00,-4.924039e-01,8.682409e-02,0.173648,0.984808,0.666052,0.897984,1.118034,26.717474,NaN,26.717474
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,43.00,43.50,100,43.00,43.75,170,0.50,0.75,-4.698463e-01,-1.710101e-01,0.704769,-0.256515,1.174616,-0.085505,1.177724,177.918276,-2.089091,177.918276
103,45.75,46.25,30,45.75,47.00,5,0.50,1.25,2.500000e-01,4.330127e-01,1.231010,0.217060,0.981010,-0.215952,1.004498,173.792660,-6.411276,173.792660
104,45.25,46.00,135,44.25,45.50,155,0.75,1.25,-1.377728e-16,-7.500000e-01,0.803485,-0.957556,0.803485,-0.207556,0.829859,172.758010,-7.571829,172.758010
105,46.00,46.50,40,46.25,48.00,5,0.50,1.75,8.682409e-02,4.924039e-01,1.723414,0.303884,1.636589,-0.188520,1.647412,176.714516,-3.314678,176.714516
106,42.25,42.75,110,42.00,42.25,65,0.50,0.25,-3.830222e-01,-3.213938e-01,-0.160697,0.191511,0.222325,0.512905,0.559017,33.282526,NaN,33.282526