<a href="https://colab.research.google.com/github/drskprabhakar/AI-ML-DL-colab-notebooks-coding-models/blob/main/Kalyani_study_patients_3725.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_excel('/content/drive/MyDrive/Kalyani STUDY PATIENT.xlsx')

In [5]:
df.shape

(174, 27)

In [6]:
df.columns

Index(['IP NUMBER ', 'NAME ', 'AGE', 'SEX', 'DIAGNOSIS', 'KH', 'KV', 'AX',
       'AL', 'ACD', 'LT', 'V/A PRE OP', 'POD 1 DAY V/A', 'SPH', 'CYL', 'AXIS',
       'POD 1 DAY  AR ', 'POD 6 WEEK V/A ', 'SPH ', 'CYL.1', 'AXIS.1',
       'POD 6 WEEK   AR ', 'POD 3 MONTH V/A', 'SPH.1', 'CYL ', 'AXIS.2',
       'POD 3  MONTH    AR'],
      dtype='object')

In [19]:
# prompt: Correlate KH, KV, AL

df[['AGE', 'SEX_numeric', 'KH','KV','AL','ACD','LT']].corr()

,AGE,SEX_numeric,KH,KV,AL,ACD,LT
AGE,1.000000,-0.023174,-0.046160,-0.030378,0.030634,-0.052509,0.030241
SEX_numeric,-0.023174,1.000000,-0.159454,-0.104715,0.152359,0.063168,0.073170
KH,-0.046160,-0.159454,1.000000,0.853545,-0.582283,0.018138,0.015894
KV,-0.030378,-0.104715,0.853545,1.000000,-0.476841,0.090135,-0.023622
AL,0.030634,0.152359,-0.582283,-0.476841,1.000000,0.177597,-0.007179
ACD,-0.052509,0.063168,0.018138,0.090135,0.177597,1.000000,-0.464393
LT,0.030241,0.073170,0.015894,-0.023622,-0.007179,-0.464393,1.000000

In [16]:
# prompt: Correlate AGE and SEX

# Convert 'SEX' column to numerical representation
df['SEX_numeric'] = df['SEX'].astype('category').cat.codes

# Correlate AGE and the new numerical SEX column
print(df[['AGE', 'SEX_numeric']].corr())

# You can drop the temporary 'SEX_numeric' column if not needed further
# df = df.drop('SEX_numeric', axis=1)

                  AGE  SEX_numeric
AGE          1.000000    -0.023174
SEX_numeric -0.023174     1.000000

In [18]:
# prompt: Correlate AGE and SEX

df[['AGE', 'SEX_numeric']].corr()

                  AGE  SEX_numeric
AGE          1.000000    -0.023174
SEX_numeric -0.023174     1.000000

In [17]:
df

,IP NUMBER,NAME,AGE,SEX,DIAGNOSIS,KH,KV,AX,AL,ACD,...,SPH,CYL.1,AXIS.1,POD 6 WEEK AR,POD 3 MONTH V/A,SPH.1,CYL,AXIS.2,POD 3 MONTH AR,SEX_numeric
0,2682458,NAGAMMA,54,F,LE MC,46.50,47.25,155,22.65,2.76,...,0.25,-1.25,100.0,+0.25/-1.25/100,6\9,0.50,-1.00,65.0,+0.50/-1.00/65,0
1,2682462,GOWRAMMA,63,F,LE MC,46.75,48.00,80,21.90,1.99,...,0.75,-2.00,90.0,+0.75/-2.00/90,6\12,0.50,-2.00,80.0,+0.50/-2.00/80,0
2,2682451,SUNDRAMMA,78,F,RE BROWN CATARACT,44.00,44.25,20,22.91,3.08,...,-1.5,-1.00,140.0,-1.50/-1.00/140,NaN,NaN,NaN,NaN,NaN,0
3,2683506,KUNNABASAMMA,71,F,RE NS II + PSC,45.25,45.75,120,22.32,3.48,...,-0.5,-0.75,140.0,-0.5/-0.75/140,6\9,-0.50,-0.50,150.0,-0.5/-0.50/150,0
4,2689441,SANNAIAH,89,M,LE NS II + PSC + CC,45.50,47.00,80,22.31,3.06,...,0.25,2.25,85.0,+0.25/+2.25/85,NaN,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169,2882449,JAYASHANKAR,54,M,LE PSC + CC,45.00,46.25,165,23.01,3.47,...,-2,-2.50,110.0,-2/-2.5/110,6\12,-1.75,-2.25,90.0,-1.75/-2.25/90,1
170,2898829,NINGEGOWDA,57,M,RE NMC,41.00,42.50,85,23.35,3.39,...,-2,-1.25,90.0,-2/-1.25/90,6\9,-1.00,-1.25,65.0,-1/-1.25/65,1
171,1706142,MARIHUCHAIAH,72,M,LE NS II + PSC + CC,44.75,45.75,75,22.07,3.16,...,-2.5,-4.25,10.0,-2.5/-4.25/10,NaN,NaN,NaN,NaN,NaN,1
172,2903314,REVANNA,74,M,LE NS III,44.75,45.25,170,23.36,3.38,...,-1,3.25,150.0,-1/+3.25/150,NaN,NaN,NaN,NaN,NaN,1
173,2793975,NANJAIAH,52,M,LE NS I + PSC,44.75,44.75,180,23.01,3.20,...,-3.5,-2.75,75.0,-3.50/-2.75/75,NaN,NaN,NaN,NaN,NaN,1

In [81]:
# prompt: Linear regression

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
X = df[['AGE','ACD', 'SEX_numeric', 'KH', 'KH', 'LT']]  # Features
y = df['AL']   # Target (let's predict AL based on AGE)

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Create a linear regression model
model = LinearRegression()

# Train the model
model.fit(X_train, y_train)

# Make predictions
predictions = model.predict(X_test)

# Evaluate the model (optional)
from sklearn.metrics import mean_squared_error, r2_score
print('Mean squared error:', mean_squared_error(y_test, predictions))
print('R2 score:', r2_score(y_test, predictions))

Mean squared error: 0.35759070010503635
R2 score: 0.4777415528557818

In [82]:
# prompt: OLS

import statsmodels.api as sm

# Add a constant to the features (for the intercept)
X = sm.add_constant(X)

# Create an OLS model
ols_model = sm.OLS(y, X)

# Fit the model
results = ols_model.fit()

# Print the summary of the results
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                     AL   R-squared:                       0.451
Model:                            OLS   Adj. R-squared:                  0.434
Method:                 Least Squares   F-statistic:                     26.65
Date:                Thu, 03 Jul 2025   Prob (F-statistic):           1.34e-19
Time:                        02:37:12   Log-Likelihood:                -137.70
No. Observations:                 168   AIC:                             287.4
Df Residuals:                     162   BIC:                             306.1
Df Model:                           5
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const          32.4951      1.379     23.557      0.000      29.771      35.219
AGE             0.0010      0.005      0.232      0.817      -0.008       0.010
ACD             0.4731      0.112      4.232      0.000       0.252       0.694
SEX_numeric     0.0819      0.091      0.901      0.369      -0.098       0.261
KH             -0.1391      0.013    -10.327      0.000      -0.166      -0.113
KH             -0.1391      0.013    -10.327      0.000      -0.166      -0.113
LT              0.2366      0.089      2.655      0.009       0.061       0.413
==============================================================================
Omnibus:                        1.959   Durbin-Watson:                   1.910
Prob(Omnibus):                  0.376   Jarque-Bera (JB):                1.718
Skew:                           0.026   Prob(JB):                        0.424
Kurtosis:                       3.493   Cond. No.                     2.31e+17
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.56e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [84]:
# prompt: Polynomials

from sklearn.preprocessing import PolynomialFeatures

# Create polynomial features (e.g., degree 2)
poly_features = PolynomialFeatures(degree=2)
X_poly = poly_features.fit_transform(X)

# Split data into training and testing sets for polynomial regression
X_train_poly, X_test_poly, y_train_poly, y_test_poly = train_test_split(X_poly, y, test_size=0.3, random_state=42)

# Create a linear regression model with polynomial features
poly_model = LinearRegression()

# Train the model
poly_model.fit(X_train_poly, y_train_poly)

# Make predictions
predictions_poly = poly_model.predict(X_test_poly)

# Evaluate the polynomial model
print('Mean squared error (Polynomial):', mean_squared_error(y_test_poly, predictions_poly))
print('R2 score (Polynomial):', r2_score(y_test_poly, predictions_poly))

# You can also use statsmodels for a summary of the polynomial regression
# Add a constant to the polynomial features
X_poly = sm.add_constant(X_poly)

# Create an OLS model with polynomial features
ols_poly_model = sm.OLS(y, X_poly)

# Fit the model
results_poly = ols_poly_model.fit()

# Print the summary of the results
print(results_poly.summary())

Mean squared error (Polynomial): 0.3422052504965626
R2 score (Polynomial): 0.5002118828134035
                            OLS Regression Results
==============================================================================
Dep. Variable:                     AL   R-squared:                       0.527
Model:                            OLS   Adj. R-squared:                  0.467
Method:                 Least Squares   F-statistic:                     8.689
Date:                Thu, 03 Jul 2025   Prob (F-statistic):           4.40e-16
Time:                        02:38:14   Log-Likelihood:                -125.18
No. Observations:                 168   AIC:                             290.4
Df Residuals:                     148   BIC:                             352.8
Df Model:                          19
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         10.9836      9.780      1.123      0.263      -8.343      30.310
x1            10.9836      9.780      1.123      0.263      -8.343      30.310
x2             0.0908      0.093      0.977      0.330      -0.093       0.274
x3             1.4696      1.918      0.766      0.445      -2.320       5.259
x4             1.7650      0.978      1.804      0.073      -0.169       3.699
x5            -0.1396      0.262     -0.534      0.594      -0.657       0.377
x6            -0.1396      0.262     -0.534      0.594      -0.657       0.377
x7            -1.0410      1.388     -0.750      0.454      -3.784       1.702
x8            10.9836      9.780      1.123      0.263      -8.343      30.310
x9             0.0908      0.093      0.977      0.330      -0.093       0.274
x10            1.4696      1.918      0.766      0.445      -2.320       5.259
x11            1.7650      0.978      1.804      0.073      -0.169       3.699
x12           -0.1396      0.262     -0.534      0.594      -0.657       0.377
x13           -0.1396      0.262     -0.534      0.594      -0.657       0.377
x14           -1.0410      1.388     -0.750      0.454      -3.784       1.702
x15           -0.0005      0.000     -1.230      0.221      -0.001       0.000
x16            0.0160      0.013      1.210      0.228      -0.010       0.042
x17           -0.0017      0.009     -0.179      0.858      -0.020       0.017
x18           -0.0012      0.002     -0.677      0.500      -0.005       0.002
x19           -0.0012      0.002     -0.677      0.500      -0.005       0.002
x20           -0.0178      0.012     -1.434      0.154      -0.042       0.007
x21           -0.0820      0.145     -0.566      0.572      -0.369       0.204
x22           -0.6670      0.269     -2.479      0.014      -1.199      -0.135
x23           -0.0320      0.042     -0.764      0.446      -0.115       0.051
x24           -0.0320      0.042     -0.764      0.446      -0.115       0.051
x25            0.0398      0.162      0.246      0.806      -0.280       0.359
x26            1.7650      0.978      1.804      0.073      -0.169       3.699
x27           -0.0149      0.028     -0.541      0.590      -0.070       0.040
x28           -0.0149      0.028     -0.541      0.590      -0.070       0.040
x29           -0.4214      0.204     -2.068      0.040      -0.824      -0.019
x30            0.0016      0.004      0.442      0.659      -0.006       0.009
x31            0.0016      0.004      0.442      0.659      -0.006       0.009
x32            0.0286      0.030      0.962      0.338      -0.030       0.087
x33            0.0016      0.004      0.442      0.659      -0.006       0.009
x34            0.0286      0.030      0.962      0.338      -0.030       0.087
x35            0.1077      0.115      0.937      0.350      -0.119       0.335
==============================================================================
Omnibus:                        2.622   Durbin-Watson:                   1.987
Prob(Omnibus):                  0.270   Jarque-Bera (JB):                2.655
Skew:                           0.014   Prob(JB):                        0.265
Kurtosis:                       3.615   Cond. No.                     4.38e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 4.08e-24. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [92]:
# prompt: Linear regression

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
# Corrected: Removed the duplicate 'KH' column
X = df[['AGE','ACD', 'SEX_numeric', 'KH', 'LT']]  # Features
y = df['AL']   # Target (let's predict AL based on AGE)

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Create a linear regression model
model = LinearRegression()

# Train the model
model.fit(X_train, y_train)

# Make predictions
predictions = model.predict(X_test)

# Evaluate the model (optional)
from sklearn.metrics import mean_squared_error, r2_score
print('Mean squared error:', mean_squared_error(y_test, predictions))
print('R2 score:', r2_score(y_test, predictions))

# prompt: OLS

import statsmodels.api as sm

# Add a constant to the features (for the intercept)
# Re-add the constant to the corrected X DataFrame
X_ols = sm.add_constant(X)

# Create an OLS model
ols_model = sm.OLS(y, X_ols)

# Fit the model
results = ols_model.fit()

# Print the summary of the results
print(results.summary())


# prompt: Polynomials

from sklearn.preprocessing import PolynomialFeatures

# Create polynomial features (e.g., degree 2)
poly_features = PolynomialFeatures(degree=2)
# Use the corrected X DataFrame for polynomial features
X_poly = poly_features.fit_transform(X)

# Split data into training and testing sets for polynomial regression
X_train_poly, X_test_poly, y_train_poly, y_test_poly = train_test_split(X_poly, y, test_size=0.3, random_state=42)

# Create a linear regression model with polynomial features
poly_model = LinearRegression()

# Train the model
poly_model.fit(X_train_poly, y_train_poly)

# Make predictions
predictions_poly = poly_model.predict(X_test_poly)

# Evaluate the polynomial model
print('Mean squared error (Polynomial):', mean_squared_error(y_test_poly, predictions_poly))
print('R2 score (Polynomial):', r2_score(y_test_poly, predictions_poly))

# You can also use statsmodels for a summary of the polynomial regression
# Add a constant to the polynomial features
X_poly_ols = sm.add_constant(X_poly)

# Create an OLS model with polynomial features
ols_poly_model = sm.OLS(y, X_poly_ols)

# Fit the model
results_poly = ols_poly_model.fit()

# Print the summary of the results
print(results_poly.summary())


# prompt: XGboost

!pip install xgboost

import xgboost as xgb

# Create an XGBoost Regressor model
xgb_model = xgb.XGBRegressor(objective='reg:squarederror', n_estimators=100, learning_rate=0.1, max_depth=5, random_state=42)

# Train the XGBoost model
# Use the corrected X_train and y_train
xgb_model.fit(X_train, y_train)

# Make predictions with XGBoost
predictions_xgb = xgb_model.predict(X_test)

# Evaluate the XGBoost model
print('Mean squared error (XGBoost):', mean_squared_error(y_test, predictions_xgb))
print('R2 score (XGBoost):', r2_score(y_test, predictions_xgb))

# Feature Importance (optional)
print("Feature Importances:")
# Update the column names for feature importance based on the corrected X
for i, col in enumerate(X.columns):
    print(f"{col}: {xgb_model.feature_importances_[i]}")

Mean squared error: 0.35759070010503596
R2 score: 0.47774155285578235
                            OLS Regression Results
==============================================================================
Dep. Variable:                     AL   R-squared:                       0.451
Model:                            OLS   Adj. R-squared:                  0.434
Method:                 Least Squares   F-statistic:                     26.65
Date:                Thu, 03 Jul 2025   Prob (F-statistic):           1.34e-19
Time:                        02:43:39   Log-Likelihood:                -137.70
No. Observations:                 168   AIC:                             287.4
Df Residuals:                     162   BIC:                             306.1
Df Model:                           5
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const          32.4951      1.379     23.557      0.000      29.771      35.219
AGE             0.0010      0.005      0.232      0.817      -0.008       0.010
ACD             0.4731      0.112      4.232      0.000       0.252       0.694
SEX_numeric     0.0819      0.091      0.901      0.369      -0.098       0.261
KH             -0.2783      0.027    -10.327      0.000      -0.331      -0.225
LT              0.2366      0.089      2.655      0.009       0.061       0.413
==============================================================================
Omnibus:                        1.959   Durbin-Watson:                   1.910
Prob(Omnibus):                  0.376   Jarque-Bera (JB):                1.718
Skew:                           0.026   Prob(JB):                        0.424
Kurtosis:                       3.493   Cond. No.                     2.51e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.51e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
Mean squared error (Polynomial): 0.34220525049657596
R2 score (Polynomial): 0.5002118828133839
                            OLS Regression Results
==============================================================================
Dep. Variable:                     AL   R-squared:                       0.527
Model:                            OLS   Adj. R-squared:                  0.467
Method:                 Least Squares   F-statistic:                     8.689
Date:                Thu, 03 Jul 2025   Prob (F-statistic):           4.40e-16
Time:                        02:43:39   Log-Likelihood:                -125.18
No. Observations:                 168   AIC:                             290.4
Df Residuals:                     148   BIC:                             352.8
Df Model:                          19
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         32.9508     29.340      1.123      0.263     -25.028      90.930
x1             0.1815      0.186      0.977      0.330      -0.185       0.548
x2             2.9392      3.836      0.766      0.445      -4.641      10.519
x3             2.6476      1.468      1.804      0.073      -0.253       5.548
x4            -0.5584      1.046     -0.534      0.594      -2.626       1.510
x5            -2.0819      2.776     -0.750      0.454      -7.567       3.403
x6            -0.0005      0.000     -1.230      0.221      -0.001       0.000
x7             0.0160      0.013      1.210      0.228      -0.010       0.042
x8            -0.0017      0.009     -0.179      0.858      -0.020       0.017
x9            -0.0024      0.004     -0.677      0.500      -0.010       0.005
x10           -0.0178      0.012     -1.434      0.154      -0.042       0.007
x11           -0.0820      0.145     -0.566      0.572      -0.369       0.204
x12           -0.6670      0.269     -2.479      0.014      -1.199      -0.135
x13           -0.0640      0.084     -0.764      0.446      -0.230       0.102
x14            0.0398      0.162      0.246      0.806      -0.280       0.359
x15            2.6476      1.468      1.804      0.073      -0.253       5.548
x16           -0.0299      0.055     -0.541      0.590      -0.139       0.079
x17           -0.4214      0.204     -2.068      0.040      -0.824      -0.019
x18            0.0048      0.011      0.442      0.659      -0.017       0.026
x19            0.0573      0.060      0.962      0.338      -0.060       0.175
x20            0.1077      0.115      0.937      0.350      -0.119       0.335
==============================================================================
Omnibus:                        2.622   Durbin-Watson:                   1.987
Prob(Omnibus):                  0.270   Jarque-Bera (JB):                2.655
Skew:                           0.014   Prob(JB):                        0.265
Kurtosis:                       3.615   Cond. No.                     5.71e+19
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.59e-30. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
Requirement already satisfied: xgboost in /usr/local/lib/python3.11/dist-packages (2.1.4)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from xgboost) (2.0.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.11/dist-packages (from xgboost) (2.21.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from xgboost) (1.15.3)
Mean squared error (XGBoost): 0.3904228643634255
R2 score (XGBoost): 0.4297904313167328
Feature Importances:
AGE: 0.09178990125656128
ACD: 0.13634169101715088
SEX_numeric: 0.0500987283885479
KH: 0.5582237243652344
LT: 0.16354593634605408